version: '3.9'

services:
  springsecuritydemoapp:
    build: .
    container_name: spring-security-demo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/spring_security
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234qwer
    ports:
      - "8080:8080"
    volumes:
      - local_pgdata:/var/lib/postgresql/data


volumes:
  local_pgdata: